#pragma once

#include "CoreMinimal.h"
#include "RTPlanSchema.generated.h"

/**
 * RTPlanSchema.h
 * Defines the canonical data structures for the PlanDocument.
 * These structs are serialized to JSON and replicated across the network.
 */

// Stable ID type (using GUID for uniqueness across sessions/clients)
// Note: UHT doesn't support type aliases in UPROPERTY, so we use FGuid directly in structs.
// using FRTId = FGuid;

UENUM(BlueprintType)
enum class ERTOpeningType : uint8
{
	Door,
	Window,
	Opening // Just a hole
};

UENUM(BlueprintType)
enum class ERTHostType : uint8
{
	Floor,
	Wall,
	Ceiling,
	None
};

/**
 * 2D Vertex for wall endpoints.
 */
USTRUCT(BlueprintType)
struct RTPLANCORE_API FRTVertex
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FGuid Id;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FVector2D Position = FVector2D::ZeroVector;

	bool operator==(const FRTVertex& Other) const { return Id == Other.Id; }
};

/**
 * Wall definition.
 * Direction is from VertexA to VertexB.
 * Left/Right is relative to this direction.
 */
USTRUCT(BlueprintType)
struct RTPLANCORE_API FRTWall
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FGuid Id;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FGuid VertexAId;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FGuid VertexBId;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float ThicknessCm = 20.0f;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float HeightCm = 300.0f;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float BaseZCm = 0.0f;

	// Material/Finish IDs (referencing Catalog)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FName FinishLeftId;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FName FinishRightId;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FName FinishCapsId;
};

/**
 * Opening (Door/Window) hosted on a wall.
 */
USTRUCT(BlueprintType)
struct RTPLANCORE_API FRTOpening
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FGuid Id;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FGuid WallId;

	// Distance from VertexA along the wall vector
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float OffsetCm = 0.0f;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float WidthCm = 90.0f;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float HeightCm = 210.0f;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float SillHeightCm = 0.0f;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	ERTOpeningType Type = ERTOpeningType::Door;

	// Asset reference ID from Catalog
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FName ProductTypeId;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	bool bFlip = false;
};

/**
 * Interior Object Instance (Furniture, etc.)
 */
USTRUCT(BlueprintType)
struct RTPLANCORE_API FRTInteriorInstance
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FGuid Id;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FName ProductTypeId;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FTransform Transform = FTransform::Identity;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	ERTHostType HostType = ERTHostType::Floor;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FGuid HostWallId; // If HostType == Wall

	// If generated by a procedural run, this tracks which one.
	// If 0 (invalid), it is a manually placed object.
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FGuid GeneratedByRunId;

	// Per-instance overrides (e.g. material variants)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	TMap<FName, FString> Params;
};

/**
 * Procedural Cabinet/Wardrobe Run
 */
USTRUCT(BlueprintType)
struct RTPLANCORE_API FRTCabinetRun
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FGuid Id;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FGuid HostWallId;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float StartOffsetCm = 0.0f;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float EndOffsetCm = 0.0f;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float DepthCm = 60.0f;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	float HeightCm = 90.0f;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FName StyleSetId;
};

/**
 * Root data structure for the entire plan.
 */
USTRUCT(BlueprintType)
struct RTPLANCORE_API FRTPlanData
{
	GENERATED_BODY()

	// We use Arrays for simple serialization, but Maps might be faster for lookups.
	// For V1 with reasonable item counts, Arrays + Helper Maps in the Document class is a good pattern.
	// Or we can use TMap<FRTId, T> directly if supported by JSON serializer easily.
	// Unreal's TMap JSON support is decent. Let's use TMap for O(1) lookups.

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	TMap<FGuid, FRTVertex> Vertices;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	TMap<FGuid, FRTWall> Walls;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	TMap<FGuid, FRTOpening> Openings;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	TMap<FGuid, FRTInteriorInstance> Objects;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	TMap<FGuid, FRTCabinetRun> Runs;

	// Versioning
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int32 Version = 1;

	void Clear()
	{
		Vertices.Empty();
		Walls.Empty();
		Openings.Empty();
		Objects.Empty();
		Runs.Empty();
		Version = 1;
	}
};
